### ISSUE TITLE
cant load previous saved files

### ISSUE THREAD

**Issue by Arytas** [relu91/niftyeditor#27]
I am currently wokring on my Menu in my game and tried out the nifty editor
but if i save the current stuff, i cannot reload the file
got a huge amount of errors in my console 

(i used niftyeditor 0.6 and also 0.59)

like this
WARNING: screen [GScreen0] not found

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<nifty>
    <useControls filename="nifty-default-controls.xml"/>
    <useStyles filename="nifty-default-styles.xml"/>
    <screen id="GScreen1">
        <layer id="mainmenu" childLayout="vertical" backgroundImage="D:\Dropbox\Game Development\Nifty Gui Editor\background.png">
            <image id="header" filename="D:\Dropbox\Game Development\Nifty Gui Editor\Brick _ _ Breaker logo.png" width="80%" x="558" y="74" valign="top" align="center" height="20%"/>
            <panel id="pnl_bottom" childLayout="absolute" width="100%" valign="bottom" align="left" height="80%">
                <panel id="GPanel3" childLayout="vertical" width="405px" x="368" y="45" height="408px">
                    <panel id="GPanel4" childLayout="vertical" width="100%" style="nifty-panel-simple" align="right" height="60px"/>
                </panel>
            </panel>
        </layer>
    </screen>
</nifty>
```

Jun 13, 2016 10:43:42 AM de.lessvoid.nifty.render.NiftyMouseImpl registerMouseCursor
WARNING: Your RenderDevice does not support the createMouseCursor() method. Mouse cursors can't be changed.
Jun 13, 2016 10:43:42 AM de.lessvoid.nifty.render.NiftyMouseImpl registerMouseCursor
WARNING: Your RenderDevice does not support the createMouseCursor() method. Mouse cursors can't be changed.
Jun 13, 2016 10:43:42 AM de.lessvoid.nifty.loaderv2.types.ScreenType create
WARNING: Missing ScreenController for screen [GScreen1] using DefaultScreenController() instead but this might not be what you want.
Jun 13, 2016 10:43:42 AM jada.ngeditor.controller.GUIEditor$Reload perform
SEVERE: null
java.lang.RuntimeException: java.lang.IllegalArgumentException: input == null!
    at de.lessvoid.nifty.Nifty.loadFromStream(Nifty.java:632)

**Comment by Arytas** [comment]
i downloaded the sources and after fixing tons of problems i was able to run in jme
there occourse this error
WARNING: screen [GScreen0] not found
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at jada.ngeditor.model.GUI$2.perform(GUI.java:226)

**Comment by Arytas** [comment]
maybe the problem is cause you using java 1.6 in dev?

**Comment by relu91** [comment]
I've tried to load your file, are you sure that you have the images in the dropbox folder? I don't think it's a java version problem. Nifty-editor has 1.6 for target jvm version.

**Comment by Arytas** [comment]
yes the settings are all correct

i found a workaround
start editor > click WorkGUI > delete GScreen0 > load XML file
with this i have no trouble to load the file
